# Generated by Django 3.2.8 on 2021-12-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('question_id', models.CharField(max_length=200)),
                ('annotation', models.CharField(max_length=200)),
                ('selection', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
