# Generated by Django 3.2.8 on 2021-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211206_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationlog',
            name='question',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
